<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '127.0.0.1',
    2 => 'mynextcloud',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://mynextcloud/nextcloud',
  'dbtype' => 'mysql',
  'version' => '18.0.9.1',
  'dbname' => 'mynextcloud',
  'dbhost' => '10.220.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'mynextcloud',
  'dbpassword' => 'mypasswdmysql',
  'installed' => true,
  'maintenance' => false,
  'overwritewebroot' => '/nextcloud',
  'overwriteprotocol' => 'https',
  'loglevel' => 2,
  'theme' => '',
  'config_is_read_only' => false,
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'smtp',
);
